name: Hargassner_NodeJS_Adapter CI-pipeline

on:
  push:
    branches: [ "master", "feat/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install eslint textlint
    - run: npm run lint
    - run: npx eslint index.js
    - run: npx textlint README.md

  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test
  
  integrationtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install hargassner_telnet
    - run: sudo node test/TestWithIntegratedSocketServer.js

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm audit --audit-level critical

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
    - run: npm install
    - run: npm run build --if-present

  functiontest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: echo "Test command line tool script"
    - run: ./test/hgboiler-cli-test.bash

  end2endtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm pack
    - run: tar -xvf hargassner_telnet-*.tgz
    - run: cd package
    - run: ls -la
    - run: npm link
    - run: ls -la
    - run: hgboiler -h
